/**
 * Regenerate utils/blurData.ts after adding or replacing images in public/.
 * Usage: node scripts/gen-blur.js
 */
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const files = [];
const walk = (d) =>
  fs.readdirSync(d, { withFileTypes: true }).forEach((e) => {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(jpg|jpeg)$/i.test(e.name)) files.push(p);
  });

walk("public/projects");
files.push("public/hero-bg.jpg");

(async () => {
  const out = {};
  for (const f of files) {
    const buf = await sharp(fs.readFileSync(f)).resize(16).jpeg({ quality: 40 }).toBuffer();
    out["/" + path.relative("public", f).split(path.sep).join("/")] =
      "data:image/jpeg;base64," + buf.toString("base64");
  }
  fs.writeFileSync(
    "utils/blurData.ts",
    '/** Generated by scripts/gen-blur.js -- tiny base64 previews for next/image placeholder="blur". */\n' +
      "export const blurMap: Record<string, string> = " +
      JSON.stringify(out, null, 2) +
      ";\n"
  );
  console.log("wrote utils/blurData.ts with", Object.keys(out).length, "entries");
})();
